fix test timeout
acquire-project/acquire-driver-zarr pull request #158
Opened 2023-11-16 21:47 UTC by aliddell

2023-11-16 22:52 UTC, nclack commented
Should there be something on the `stop()` side? What happens if `start()` gets called multiple times?

2023-11-16 22:58 UTC, andy-sweet requested changes
I'm not used to explicitly starting thread pools, but I don't hate it and it's not used much, so this seems fine to unblock the upcoming release.

My only request is around a little more guarding around the `clamp` operation in the `ThreadPool` constructor.

2023-11-16 22:58 UTC, andy-sweet commented on src/common.cpp
> +      n_threads, (size_t)1, (size_t)std::thread::hardware_concurrency());
It seems possible that [`hardware_concurrency` can return 0](https://en.cppreference.com/w/cpp/thread/thread/hardware_concurrency) and the [behavior of `clamp` is undefined when `lo > hi`](https://en.cppreference.com/w/cpp/algorithm/clamp).

So consider guarding against that (likely rare) case, by checking the return value of `hardware_concurrency` and/or using `max` of it and 1.

2023-11-16 22:58 UTC, andy-sweet commented on src/common.cpp
>  {
Optional: might want to consider checking if this has been started and similarly if it has been stopped, likely raising in both cases.

2023-11-17 16:40 UTC, andy-sweet approved these changes
Looks good now!

2023-11-17 17:20 UTC, merged